Repository icbryant9/BudgetBuddy, pull requests merged in 2020-11, with the labels that each got.

#34 BUD-13: Pie Chart
  README.md
  app/views/budgets/show.html.erb
  app/views/home/index.html.erb
Labels: enhancement

#36 Bud 73
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/navbar.css
  app/controllers/posts_controller.rb
  app/models/post.rb
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  app/views/posts/index.html.erb
  db/migrate/20201101160324_add_budgetid_to_posts.rb
  db/migrate/20201102184745_fixattachid.rb
  db/schema.rb
  test/fixtures/posts.yml
  test/models/post_test.rb
Labels: enhancement

#37 Bud 18 c - Comment Creation
  Gemfile.lock
  app/assets/stylesheets/comments.scss
  app/controllers/comments_controller.rb
  app/controllers/home_controller.rb
  app/controllers/posts_controller.rb
  app/helpers/comments_helper.rb
  app/models/comment.rb
  app/models/post.rb
  app/models/user.rb
  app/views/comments/_comment.html.erb
  app/views/comments/_form.html.erb
  app/views/comments/edit.html.erb
  app/views/home/index.html.erb
  app/views/posts/show.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  db/migrate/20201028194827_create_comments.rb
  db/schema.rb
  test/controllers/comments_controller_test.rb
  test/fixtures/comments.yml
  test/models/comment_test.rb
Labels: enhancement

#38 BUD-77 Year option on debt calculator
  app/models/calculate_debt.rb
  app/views/calculate_debts/_form.html.erb
  app/views/calculate_debts/edit.html.erb
  db/migrate/20201110011607_change_number_of_years_to_decimal.rb
  db/schema.rb
  test/fixtures/calculate_debts.yml
  test/models/calculate_debt_test.rb
Labels: enhancement

#40 Bud 80
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/rooms.scss
  app/controllers/application_controller.rb
  app/controllers/home_controller.rb
  app/views/layouts/application.html.erb
  app/views/rooms/index.html.erb
  app/views/users/show.html.erb
Labels: enhancement

#41 BUD-52
  app/models/budget.rb
  app/views/budgets/show.html.erb
  app/views/goals/index.html.erb
  app/views/goals/show.html.erb
Labels: bug

#42 BUD-74
  app/controllers/users_controller.rb
  app/views/home/index.html.erb
  app/views/shared/_navbar.html.erb
  app/views/users/search.html.erb
  config/routes.rb
Labels: enhancement

#43 Bud 81
  app/assets/stylesheets/user_options.scss
  app/controllers/user_options_controller.rb
  app/controllers/users_controller.rb
  app/helpers/user_options_helper.rb
  app/models/user.rb
  app/models/user_option.rb
  app/views/user_options/_form.html.erb
  app/views/user_options/_user_option.json.jbuilder
  app/views/user_options/edit.html.erb
  app/views/user_options/index.html.erb
  app/views/user_options/index.json.jbuilder
  app/views/user_options/new.html.erb
  app/views/user_options/show.html.erb
  app/views/user_options/show.json.jbuilder
  app/views/users/show.html.erb
  config/routes.rb
  db/migrate/20201112171238_create_user_options.rb
  db/migrate/20201112171421_add_user_fk_col_to_user_options.rb
  db/schema.rb
  test/controllers/user_options_controller_test.rb
  test/fixtures/user_options.yml
  test/models/user_option_test.rb
  test/system/user_options_test.rb
Labels: enhancement

#45 Bud 82
  app/assets/stylesheets/budgets.scss
  app/assets/stylesheets/hideme.scss
  app/views/budgets/index.html.erb
  app/views/budgets/new.html.erb
  app/views/budgets/show.html.erb
  app/views/calculate_debts/edit.html.erb
  app/views/calculate_debts/index.html.erb
  app/views/calculate_debts/new.html.erb
  app/views/calculate_debts/show.html.erb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/goals/_form.html.erb
  app/views/goals/edit.html.erb
  app/views/goals/index.html.erb
  app/views/goals/new.html.erb
  app/views/goals/show.html.erb
  app/views/retirements/edit.html.erb
  app/views/retirements/index.html.erb
  app/views/retirements/new.html.erb
  app/views/retirements/show.html.erb
Labels: bug

#47 Bud 76
  app/controllers/posts_controller.rb
  app/views/comments/_comment.html.erb
  app/views/comments/_form.html.erb
  app/views/posts/show.html.erb
Labels: enhancement

#50 BUD-84 shared postcard created
  README.md
  app/controllers/home_controller.rb
  app/models/calculate_debt.rb
  app/views/home/index.html.erb
  app/views/mentioned_posts/index.html.erb
  app/views/shared/_postcard.html.erb
Labels: documentation

#51 Logan's Comments
  app/controllers/comments_controller.rb
  app/controllers/home_controller.rb
  app/controllers/likes_controller.rb
  app/controllers/retirements_controller.rb
  app/models/account.rb
  app/models/comment.rb
  app/models/like.rb
  app/models/post.rb
  app/models/retirement.rb
  app/views/accounts/_form.html.erb
  app/views/accounts/index.html.erb
  app/views/accounts/show.html.erb
  app/views/comments/_comment.html.erb
  app/views/comments/_form.html.erb
  app/views/comments/edit.html.erb
  app/views/retirements/_form.html.erb
  app/views/retirements/edit.html.erb
  app/views/retirements/index.html.erb
  app/views/retirements/show.html.erb
  app/views/shared/_postcard.html.erb
  config/routes.rb
Labels: documentation

#49 Ben's Comments
  app/controllers/budgets_controller.rb
  app/controllers/categories_controller.rb
  app/controllers/goals_controller.rb
  app/controllers/groups_controller.rb
  app/models/budget.rb
  app/models/goal.rb
  app/models/group.rb
  app/views/budgets/_form.html.erb
  app/views/budgets/edit.html.erb
  app/views/budgets/index.html.erb
  app/views/budgets/new.html.erb
  app/views/budgets/show.html.erb
  app/views/categories/_form.html.erb
  app/views/categories/edit.html.erb
  app/views/categories/new.html.erb
  app/views/goals/_form.html.erb
  app/views/goals/edit.html.erb
  app/views/goals/index.html.erb
  app/views/goals/new.html.erb
  app/views/goals/show.html.erb
  app/views/groups/_form.html.erb
  app/views/groups/edit.html.erb
  app/views/groups/new.html.erb
  app/views/shared/_navbar.html.erb
  config/schedule.rb
  lib/tasks/groups.rake
Labels: documentation
