Repository icbryant9/BudgetBuddy, pull requests merged in 2020-10, with the labels that each got.

#9 Bud 38 - Fix Access to Retirement Index per User
  app/controllers/retirements_controller.rb
  app/models/retirement.rb
  app/models/user.rb
  app/views/home/index.html.erb
  app/views/retirements/_form.html.erb
  app/views/shared/_navbar.html.erb
  db/migrate/20200930001812_add_user_fk_col_to_retirements.rb
  db/schema.rb
  db/seeds.rb
  test/fixtures/retirements.yml
  test/models/retirement_test.rb
Labels: bug

#10 Bud 4
  app/assets/stylesheets/accounts.scss
  app/controllers/accounts_controller.rb
  app/controllers/retirements_controller.rb
  app/helpers/accounts_helper.rb
  app/models/account.rb
  app/models/user.rb
  app/views/accounts/_account.json.jbuilder
  app/views/accounts/_form.html.erb
  app/views/accounts/edit.html.erb
  app/views/accounts/index.html.erb
  app/views/accounts/index.json.jbuilder
  app/views/accounts/new.html.erb
  app/views/accounts/show.html.erb
  app/views/accounts/show.json.jbuilder
  app/views/shared/_navbar.html.erb
  config/routes.rb
  db/migrate/20201001210204_create_accounts.rb
  db/migrate/20201001212538_add_user_fk_col_to_accounts.rb
  db/schema.rb
  test/controllers/accounts_controller_test.rb
  test/fixtures/accounts.yml
  test/models/account_test.rb
  test/system/accounts_test.rb
Labels: enhancement

#11 BUD-7
  app/assets/images/2020_meme.jpg
  app/assets/images/info.png
  app/assets/images/logo1.png
  app/assets/images/plus.png
  app/assets/stylesheets/goals.scss
  app/models/goal.rb
  app/views/announcements/index.html.erb
  app/views/goals/_form.html.erb
  app/views/goals/edit.html.erb
  app/views/goals/index.html.erb
  app/views/goals/show.html.erb
  app/views/home/privacy.html.erb
  app/views/home/terms.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_head.html.erb
  app/views/shared/_navbar.html.erb
  config/application.rb
  db/migrate/20200925204844_create_goals.rb
  db/schema.rb
  db/seeds.rb
  test/fixtures/goals.yml
  test/models/goal_test.rb
Labels: enhancement

#12 BUD-47
  README.md
Labels: documentation

#14 Bud-48
  Gemfile
  app/controllers/accounts_controller.rb
  app/models/calculate_debt.rb
  app/views/calculate_debts/_form.html.erb
  app/views/calculate_debts/edit.html.erb
  app/views/calculate_debts/index.html.erb
  app/views/calculate_debts/new.html.erb
  app/views/home/index.html.erb
Labels: enhancement

#16 Bud 29
  app/assets/stylesheets/follows.scss
  app/assets/stylesheets/user.scss
  app/controllers/follows_controller.rb
  app/controllers/users_controller.rb
  app/helpers/follows_helper.rb
  app/helpers/user_helper.rb
  app/models/follow.rb
  app/models/user.rb
  app/views/follows/_follow.json.jbuilder
  app/views/follows/_form.html.erb
  app/views/follows/edit.html.erb
  app/views/follows/index.html.erb
  app/views/follows/index.json.jbuilder
  app/views/follows/new.html.erb
  app/views/follows/show.html.erb
  app/views/follows/show.json.jbuilder
  app/views/home/index.html.erb
  app/views/users/index.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  db/migrate/20201008160857_create_follows.rb
  db/migrate/20201008161615_add_user_fk_col_to_follows.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/follows_controller_test.rb
  test/controllers/user_controller_test.rb
  test/fixtures/follows.yml
  test/models/follow_test.rb
  test/system/follows_test.rb
Labels: enhancement

#17 Bud-30
  app/assets/stylesheets/userpop.css
  app/controllers/follows_controller.rb
  app/views/users/index.html.erb
  app/views/users/show.html.erb
Labels: enhancement

#18 Bud 10
  app/assets/stylesheets/likes.scss
  app/assets/stylesheets/posts.scss
  app/assets/stylesheets/socials.scss
  app/controllers/likes_controller.rb
  app/controllers/posts_controller.rb
  app/controllers/socials_controller.rb
  app/helpers/likes_helper.rb
  app/helpers/posts_helper.rb
  app/helpers/socials_helper.rb
  app/models/like.rb
  app/models/post.rb
  app/models/user.rb
  app/views/posts/_form.html.erb
  app/views/posts/_post.json.jbuilder
  app/views/posts/edit.html.erb
  app/views/posts/index.html.erb
  app/views/posts/index.json.jbuilder
  app/views/posts/new.html.erb
  app/views/posts/show.html.erb
  app/views/posts/show.json.jbuilder
  app/views/shared/_navbar.html.erb
  app/views/socials/index.html.erb
  config/routes.rb
  db/migrate/20201007191546_create_posts.rb
  db/migrate/20201007192507_add_user_fk_col_to_posts.rb
  db/migrate/20201007201330_create_likes.rb
  db/schema.rb
  test/controllers/likes_controller_test.rb
  test/controllers/posts_controller_test.rb
  test/controllers/socials_controller_test.rb
  test/fixtures/likes.yml
  test/fixtures/posts.yml
  test/models/like_test.rb
  test/models/post_test.rb
  test/system/posts_test.rb
Labels: enhancement

#21 Updated Account edit action and view. This is now complete
  app/assets/images/edit.png
  app/views/accounts/index.html.erb
Labels: enhancement

#22 Bud 50 Added like functionality to user page and added a create a post button at the top of the page
  app/controllers/likes_controller.rb
  app/views/users/show.html.erb
Labels: enhancement

#20 BUD-49 fix
  app/controllers/users_controller.rb
  app/views/users/show.html.erb
Labels: bug

#23 Bud 21
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/navbar.css
  app/assets/stylesheets/userpop.css
  app/controllers/home_controller.rb
  app/javascript/packs/application.js
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_navbar.html.erb
  app/views/users/show.html.erb
Labels: enhancement

#24 Bud 33
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/userpop.css
  app/controllers/goals_controller.rb
  app/controllers/home_controller.rb
  app/controllers/posts_controller.rb
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  app/views/posts/create.js.erb
  app/views/users/index.html.erb
  app/views/users/show.html.erb
Labels: enhancement

#25 BUD-2: Create Budget
  app/assets/stylesheets/budgets.scss
  app/assets/stylesheets/categories.scss
  app/assets/stylesheets/groups.scss
  app/controllers/budgets_controller.rb
  app/controllers/categories_controller.rb
  app/controllers/groups_controller.rb
  app/helpers/budgets_helper.rb
  app/helpers/categories_helper.rb
  app/helpers/groups_helper.rb
  app/models/budget.rb
  app/models/category.rb
  app/models/group.rb
  app/models/user.rb
  app/views/budgets/_budget.json.jbuilder
  app/views/budgets/_form.html.erb
  app/views/budgets/edit.html.erb
  app/views/budgets/index.html.erb
  app/views/budgets/index.json.jbuilder
  app/views/budgets/new.html.erb
  app/views/budgets/show.html.erb
  app/views/budgets/show.json.jbuilder
  app/views/categories/_category.json.jbuilder
  app/views/categories/_form.html.erb
  app/views/categories/edit.html.erb
  app/views/categories/new.html.erb
  app/views/groups/_form.html.erb
  app/views/groups/_group.json.jbuilder
  app/views/groups/edit.html.erb
  app/views/groups/new.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
  db/migrate/20201002182222_create_budgets.rb
  db/migrate/20201006163757_create_groups.rb
  db/migrate/20201006221910_create_categories.rb
  db/migrate/20201006234212_add_budget_fk_col_to_groups.rb
  db/migrate/20201007000354_add_user_fk_col_to_budgets.rb
  db/migrate/20201011164233_add_group_fk_col_to_categories.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/budgets_controller_test.rb
  test/controllers/categories_controller_test.rb
  test/controllers/groups_controller_test.rb
  test/fixtures/budgets.yml
  test/fixtures/categories.yml
  test/fixtures/groups.yml
  test/models/budget_test.rb
  test/models/category_test.rb
  test/models/group_test.rb
  test/system/budgets_test.rb
  test/system/categories_test.rb
  test/system/groups_test.rb
Labels: enhancement

#26 BUD-53
  app/assets/images/No_user.jpeg
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_navbar.html.erb
  app/views/users/index.html.erb
  app/views/users/show.html.erb
  db/schema.rb
Labels: bug

#27 BUD-6: Update Budget
  Gemfile
  app/assets/images/left_arrow.png
  app/assets/images/right_arrow.png
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/budgets.scss
  app/javascript/packs/application.js
  app/models/budget.rb
  app/models/calculate_debt.rb
  app/models/goal.rb
  app/models/user.rb
  app/views/budgets/show.html.erb
  app/views/calculate_debts/_form.html.erb
  app/views/calculate_debts/edit.html.erb
  app/views/calculate_debts/index.html.erb
  app/views/calculate_debts/show.html.erb
  app/views/goals/_form.html.erb
  app/views/goals/index.html.erb
  app/views/retirements/_form.html.erb
  app/views/retirements/index.html.erb
  app/views/retirements/show.html.erb
  app/views/shared/_footer.html.erb
  app/views/shared/_navbar.html.erb
  db/migrate/20200925204844_create_goals.rb
  db/schema.rb
  db/seeds.rb
  test/fixtures/goals.yml
  test/models/goal_test.rb
Labels: enhancement

#28 BUD-11: Merge New Seed Data
  Gemfile
  Gemfile.lock
  app/assets/images/left_arrow.png
  app/assets/images/logo.png
  app/assets/images/right_arrow.png
  app/models/group.rb
  config/environments/development.rb
  db/seeds.rb
Labels: enhancement

#30 Bud 64
  app/controllers/home_controller.rb
  app/controllers/posts_controller.rb
  app/models/calculate_debt.rb
  app/models/post.rb
  app/views/home/index.html.erb
  app/views/posts/_form.html.erb
  app/views/posts/index.html.erb
  db/migrate/20201025230231_add_attachtype_to_posts.rb
  db/migrate/20201025230309_add_attachid_to_posts.rb
  db/schema.rb
  test/fixtures/calculate_debts.yml
  test/fixtures/posts.yml
  test/models/calculate_debt_test.rb
  test/models/post_test.rb
Labels: enhancement

#31 BUD-11: Spending Comparison
  README.md
  app/controllers/budgets_controller.rb
  app/controllers/categories_controller.rb
  app/controllers/groups_controller.rb
  app/models/category.rb
  app/models/group.rb
  app/views/budgets/index.html.erb
  app/views/budgets/show.html.erb
  app/views/groups/_form.html.erb
  config/schedule.rb
  db/migrate/20201006163757_create_groups.rb
  db/schema.rb
  db/seeds.rb
  lib/tasks/groups.rake
  test/fixtures/groups.yml
  test/models/group_test.rb
Labels: enhancement

#32 Bud 69
  Gemfile
  Gemfile.lock
  README.md
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/messages.scss
  app/assets/stylesheets/rooms.scss
  app/assets/stylesheets/trixs.scss
  app/channels/room_channel.rb
  app/controllers/application_controller.rb
  app/controllers/messages_controller.rb
  app/controllers/rooms_controller.rb
  app/helpers/messages_helper.rb
  app/helpers/rooms_helper.rb
  app/javascript/channels/room_channel.js
  app/javascript/packs/application.js
  app/jobs/send_message_job.rb
  app/models/message.rb
  app/models/room.rb
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  app/views/messages/_form.html.erb
  app/views/messages/_message.html.erb
  app/views/messages/_message.json.jbuilder
  app/views/messages/_mine.html.erb
  app/views/messages/_theirs.html.erb
  app/views/messages/create.js.erb
  app/views/messages/edit.html.erb
  app/views/messages/index.html.erb
  app/views/messages/index.json.jbuilder
  app/views/messages/new.html.erb
  app/views/messages/show.html.erb
  app/views/messages/show.json.jbuilder
  app/views/rooms/_form.html.erb
  app/views/rooms/_room.json.jbuilder
  app/views/rooms/edit.html.erb
  app/views/rooms/index.html.erb
  app/views/rooms/index.json.jbuilder
  app/views/rooms/new.html.erb
  app/views/rooms/show.html.erb
  app/views/rooms/show.json.jbuilder
  config/routes.rb
  db/migrate/20201029020649_create_rooms.rb
  db/migrate/20201029020756_create_messages.rb
  db/migrate/20201029034119_add_author_id_to_room.rb
  db/migrate/20201029040806_add_index_to_room.rb
  db/migrate/20201029044604_add_user1_user2_to_room.rb
  db/schema.rb
  test/controllers/messages_controller_test.rb
  test/controllers/rooms_controller_test.rb
  test/fixtures/messages.yml
  test/fixtures/rooms.yml
  test/models/message_test.rb
  test/models/room_test.rb
  test/system/messages_test.rb
  test/system/rooms_test.rb
Labels: enhancement
